on:
  push:
    tags:
    - "*"

name: release

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20.13.0
    - uses: actions/setup-node@v3
      with:
        node-version: 20.13.0

    # Create ./tmp
    - run: "mkdir ./tmp"

    # Unzip committed zip files into ./tmp
    - run: "unzip ./dist/chrome.zip -d ./tmp/chrome"
    - run: "unzip ./dist/firefox.zip -d ./tmp/firefox"
    - run: "unzip ./dist/website.zip -d ./tmp/website"

    # Rebuild
    - run: "npm ci && npm run build"

    # Compare unzipped content
    - run: "diff -r ./tmp/chrome ./dist/chrome"
    - run: "diff -r ./tmp/firefox ./dist/firefox"
    - run: "diff -r ./tmp/website ./dist/website"

    # Delete ./tmp
    - run: "rm -rf ./tmp"
    
    # Restore build files
    - run: "git restore ./dist"

    # Recompute IPFS hashes
    - run: "node ./scripts/ipfs.mjs"

    # Display IPFS hashes
    - run: "cat ./dist/.ipfs.md"
    - run: "cat ./dist/.website.ipfs.md"

    # Compare all files
    - run: "git status --porcelain"
    - run: "[[ -z $(git status --porcelain) ]]"