on: [push]

name: release

jobs:
  check:
    name: check
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 20.x
    - uses: actions/setup-node@v3
      with:
        node-version: 20.x
    # Create ./unzipped
    - run: "mkdir ./unzipped"
    # Unzip committed zip files into ./unzipped
    - run: "unzip ./dist/chrome.zip -d ./unzipped/chrome"
    - run: "unzip ./dist/firefox.zip -d ./unzipped/firefox"
    - run: "unzip ./dist/website.zip -d ./unzipped/website"
    # Rebuild
    - run: "npm ci && npm run build"
    # Compare unzipped committed zip files and built folders
    - run: "diff -r ./unzipped/chrome ./dist/chrome"
    - run: "diff -r ./unzipped/firefox ./dist/firefox"
    - run: "diff -r ./unzipped/website ./dist/website"
    # Delete ./unzipped
    - run: "rm -rf ./unzipped"
    # Restore build files
    - run: "git restore ./dist"
    # Recompute IPFS hashes
    - run: "node ./scripts/ipfs.mjs"
    # Compare all files
    - run: "git status --porcelain"
    - run: "[[ -z $(git status --porcelain) ]]"